name: coursist unit tests and linting
on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      args: ". --check"
    - name: Run unit tests
      run: |
        python manage.py migrate
        python manage.py test
